<?php
/**
 * @file
 * Code for the Rotternews Base feature.
 */

include_once 'rotternews_base.features.inc';
require_once 'include/RotterNews.inc';

/**
 * Import news items from Rotter.net.
 */
function rotternews_base_get_update() {
  // Get data.
  $data = rotternews_get_update_data();
  $data_by_om = array();
  $new_node_ids = array();

  foreach($data as $data_row) {
    if (!empty($data_row['om'])) {
      $data_by_om[$data_row['om']] = intval($data_row['om']);
    }
  }
  // Load candidates to cache memory.
  $old_nodes = rotternews_base_get_nodes($data_by_om);
  foreach($data as $article_data) {
    if (!$node = rotternews_base_update_article($article_data, $old_nodes)) {
      // Create a new node.
      $node = rotternews_base_create_article($article_data);
    }

    $new_node_ids[] = $node->nid;
  }

  // Set this for the next round of update.
  variable_set('rotternews_last_nodes', $new_node_ids);
}

/**
 * Create an article from given data.
 * @param array $data
 * @return object
 *  Created node.
 */
function rotternews_base_create_article($data = array()) {
  $node = new stdClass();
  $node->title = $data['title'];
  $node->type = "news_item";
  // Sets some defaults. Invokes hook_prepare() and hook_node_prepare().
  node_object_prepare($node);
  $node->language = LANGUAGE_NONE;
  $node->uid = 1;
  $node->status = 1;
  $node->promote = 0;
  $node->created = $data['timestamp'];

  $wrapper = entity_metadata_wrapper('node', $node);
  $wrapper->field_rotter_id->set(intval($data['om']));

  return _rotternews_base_save_node($wrapper->value(), $data);
}

/**
 * Update a node with given data.
 *
*@param array $data
 *  Data to update with.
 * @param array $nodes_by_om
 *  Possible nodes that could be replaced (key is om).
 * @return object/NULL
 *  NULL on fail, node object if successful.
 */
function rotternews_base_update_article($data = array(), $nodes_by_om  = array()) {
  if (empty($data['om'])) {
    return;
  }

  $node = NULL;
  if (!empty($nodes_by_om[$data['om']])) {
    $node = $nodes_by_om[$data['om']];
  }

  if (empty($node)) {
    return;
  }
  return _rotternews_base_save_node($node, $data, FALSE);
}

/**
 * Gets the latest nodes IDs that were created to cache them.
 * @param $rotter_ids array
 *  Array of the current rotter OMs that were parsed.
 * @return array
 *  Array of found, possibly relevant nodes.
 */
function rotternews_base_get_nodes($rotter_ids) {
  $query = new EntityFieldQuery();
  $result = $query
    ->entityCondition('entity_type', 'node')
    ->propertyCondition('type', 'news_item', '=')
    ->fieldCondition('field_rotter_id', 'value', $rotter_ids, 'IN')
    ->execute();

  $node_ids = array();
  if (!empty($result['node'])) {
    $node_ids += array_keys($result['node']);
  }
  $node_ids += variable_get('rotternews_last_nodes', array());

  $nodes = node_load_multiple($node_ids);

  $nodes_by_om = array();
  foreach ($nodes as $node) {
    $wrapper = entity_metadata_wrapper('node', $node);
    $nodes_by_om[$wrapper->field_rotter_id->value()] = $node;
  }

  return $nodes_by_om;
}

function _rotternews_base_save_node($node, $data, $get_first_post = TRUE) {
  $wrapper = entity_metadata_wrapper('node', $node);
  $wrapper->title->set($data['title']);
  $wrapper->field_views->set($data['views']);
  $wrapper->field_comments->set($data['comments']);

  if ($get_first_post) {
    $post_data = rotternews_get_first_post($data['href'], 0);

    $wrapper->body->set(
      array(
        'value' => $post_data,
        'summary' => '',
        'format' => 'no_filter',
      )
    );
  }

  $wrapper->save();

  return $wrapper->value();
}

/**
 * Handle Rotternews errors.
 *
 * @param int $code
 *  Error code.
 */
function rotternews_base_handle_error($code = 0, $args = array()) {
  // Get message.
  $message = _rotternews_get_error_message($code, $args);

  if (drupal_is_cli()) {
    // Error during drush call.
    drush_print($message);
  }

  // Send message to watchdog.
  watchdog("Rotternews", $message, array(), $severity = WATCHDOG_ERROR);

  return $message;
}
